#!/usr/bin/env python3
"""Generate 120 YAML configs for preprocessing sweep (20 combos × 6 regimes).

Reduced simulation parameters (N=100, Lx=Ly=15) for faster screening.
Sweeps density_transform × clamp_mode × mass_postprocess to find optimal
preprocessing for MVAR and LSTM independently.
"""

import os
import yaml
from pathlib import Path

# ── Regimes (only Cr and lr differ) ──────────────────────────────────────────
REGIMES = {
    "CS01": {"Cr": 0.1, "lr": 0.5, "label": "Collective swarm"},
    "DR01": {"Cr": 0.1, "lr": 0.1, "label": "Double ring"},
    "SM01": {"Cr": 0.5, "lr": 0.1, "label": "Single mill"},
    "DM01": {"Cr": 0.9, "lr": 0.5, "label": "Double mill"},
    "EC02": {"Cr": 3.0, "lr": 0.5, "label": "Escape collapse"},
    "ES01": {"Cr": 3.0, "lr": 0.9, "label": "Escape symmetric"},
}

# ── Reduced grid: 20 combos (skipping redundant) ────────────────────────────
# (density_transform, clamp_mode, mass_postprocess)
COMBOS = [
    # raw transform: full clamp × mass sweep
    ("raw",     "C0", "none"),       # 1  – baseline
    ("raw",     "C1", "none"),       # 2
    ("raw",     "C2", "none"),       # 3
    ("raw",     "C0", "simplex"),    # 4
    ("raw",     "C1", "simplex"),    # 5
    ("raw",     "C0", "scale"),      # 6
    ("raw",     "C1", "scale"),      # 7
    ("raw",     "C2", "scale"),      # 8
    # sqrt transform
    ("sqrt",    "C0", "none"),       # 9
    ("sqrt",    "C1", "none"),       # 10
    ("sqrt",    "C2", "none"),       # 11
    ("sqrt",    "C0", "simplex"),    # 12 – current LFIX setup
    ("sqrt",    "C1", "simplex"),    # 13
    ("sqrt",    "C0", "scale"),      # 14
    ("sqrt",    "C1", "scale"),      # 15
    ("sqrt",    "C2", "scale"),      # 16
    # log transform (smaller clamp sweep — less likely optimal)
    ("log",     "C0", "none"),       # 17
    ("log",     "C0", "simplex"),    # 18
    ("log",     "C0", "scale"),      # 19
    # meansub (baseline check only)
    ("meansub", "C0", "none"),       # 20
]


def make_config(regime_key, regime_info, transform, clamp, mass):
    """Build a config dict for one sweep point."""
    Cr = regime_info["Cr"]
    lr = regime_info["lr"]
    label = regime_info["label"]
    exp_name = f"PSW_{regime_key}_{transform}_{clamp}_{mass}"

    # Reduced-size IC positions scaled to Lx=Ly=15
    cfg = {
        # ── Header comment stored as _comment (will be written manually) ──
        "_comment": (
            f"# PSW sweep: {label} (Cr={Cr}, lr={lr})\n"
            f"# transform={transform}, clamp={clamp}, mass_postprocess={mass}\n"
            f"# Auto-generated by scripts/create_preprocess_sweep_configs.py\n"
        ),
        "sim": {
            "N": 100,
            "T": 20.0,
            "dt": 0.04,
            "Lx": 15.0,
            "Ly": 15.0,
            "bc": "periodic",
        },
        "test_sim": {"T": 100.0},
        "model": {
            "type": "discrete",
            "speed": 3.0,
            "speed_mode": "constant_with_forces",
        },
        "params": {"R": 4.0},
        "noise": {
            "kind": "gaussian",
            "eta": 0.2,
            "match_variance": True,
        },
        "forces": {
            "enabled": True,
            "type": "morse",
            "params": {
                "Ca": 1.0,
                "Cr": Cr,
                "la": 1.0,
                "lr": lr,
                "mu_t": 0.3,
                "rcut_factor": 5.0,
            },
        },
        "alignment": {"enabled": True},
        "density": {
            "nx": 48,
            "ny": 48,
            "bandwidth": 3.0,
        },
        "outputs": {
            "density_resolution": 48,
            "density_bandwidth": 3.0,
        },
        # ── Reduced training ICs (scaled to Lx=Ly=15) ──
        "train_ic": {
            "type": "mixed_comprehensive",
            "gaussian": {
                "enabled": True,
                "n_runs": 40,
                "positions_x": [3.0, 7.5, 12.0],
                "positions_y": [3.0, 7.5, 12.0],
                "variances": [1.0, 2.0, 3.5],
                "n_samples_per_config": 1,
            },
            "uniform": {
                "enabled": True,
                "n_runs": 20,
                "n_samples": 20,
            },
            "two_clusters": {
                "enabled": True,
                "n_runs": 12,
                "separations": [3.0, 5.0, 7.0],
                "sigmas": [1.0, 2.0],
                "n_samples_per_config": 2,
            },
            "ring": {
                "enabled": True,
                "n_runs": 12,
                "radii": [2.0, 3.5, 5.0],
                "widths": [0.5, 1.0],
                "n_samples_per_config": 2,
            },
        },
        "test_ic": {
            "type": "mixed_test_comprehensive",
            "gaussian": {
                "enabled": True,
                "n_runs": 1,
                "test_positions_x": [7.5],
                "test_positions_y": [7.5],
                "test_variances": [1.5],
                "n_samples_per_config": 1,
            },
            "uniform": {
                "enabled": True,
                "n_runs": 1,
            },
            "two_clusters": {
                "enabled": True,
                "n_runs": 1,
                "test_separations": [5.0],
                "test_sigmas": [1.5],
                "n_samples_per_config": 1,
            },
            "ring": {
                "enabled": True,
                "n_runs": 1,
                "test_radii": [3.5],
                "test_widths": [0.8],
                "n_samples_per_config": 1,
            },
        },
        # ── ROM section: sweep variables live here ──
        "rom": {
            "subsample": 3,
            "fixed_modes": 10,
            "density_transform": transform if transform != "raw" else "raw",
            "density_transform_eps": 1e-10,
            "shift_align": True,
            "shift_align_ref": "mean",
            "save_unaligned_pod": False,  # save disk space on sweep
            "mass_postprocess": mass,
            "models": {
                "mvar": {
                    "enabled": True,
                    "lag": 5,
                    "ridge_alpha": 0.0001,
                },
                "lstm": {
                    "enabled": True,
                    "lag": 20,
                    "hidden_units": 64,
                    "num_layers": 2,
                    "dropout": 0.1,
                    "residual": True,
                    "use_layer_norm": True,
                    "normalize_input": True,
                    "max_epochs": 150,
                    "patience": 25,
                    "learning_rate": 0.0007,
                    "batch_size": 512,
                    "gradient_clip": 5.0,
                    "weight_decay": 1e-5,
                },
            },
        },
        "eval": {
            "metrics": ["r2", "rmse"],
            "save_forecasts": False,      # save disk space
            "save_time_resolved": False,
            "forecast_start": 0.6,
            "clamp_mode": clamp,
        },
        "experiment_name": exp_name,
    }
    return cfg


def write_config(cfg, out_path):
    """Write config with comment header."""
    comment = cfg.pop("_comment")
    with open(out_path, "w") as f:
        f.write("---\n")
        f.write(comment)
        f.write("\n")
        yaml.dump(cfg, f, default_flow_style=False, sort_keys=False)


def main():
    out_dir = Path(__file__).resolve().parent.parent / "configs" / "preprocess_sweep"
    out_dir.mkdir(parents=True, exist_ok=True)

    configs_written = []
    for regime_key, regime_info in REGIMES.items():
        for transform, clamp, mass in COMBOS:
            cfg = make_config(regime_key, regime_info, transform, clamp, mass)
            fname = f"PSW_{regime_key}_{transform}_{clamp}_{mass}.yaml"
            out_path = out_dir / fname
            write_config(cfg, out_path)
            configs_written.append(fname)

    # Write a manifest for the SLURM array job
    manifest_path = out_dir / "manifest.txt"
    with open(manifest_path, "w") as f:
        for fname in configs_written:
            f.write(f"{fname}\n")

    print(f"Generated {len(configs_written)} configs in {out_dir}")
    print(f"Manifest: {manifest_path}")


if __name__ == "__main__":
    main()
