#!/usr/bin/env python3
"""Generate a focused LSTM preprocessing ablation from systematic configs.

This suite fixes the architecture to the current best performer from the size
ablation (`h64_L2`) and sweeps preprocessing / postprocessing choices on the
same six hard regimes.
"""

from __future__ import annotations

from pathlib import Path

import yaml


REPO_ROOT = Path(__file__).resolve().parent.parent
OUTPUT_DIR = REPO_ROOT / "configs" / "LSTM_preprocess_ablation"
PARTICLE_COUNT = 200

REGIMES = [
    {
        "key": "CS01",
        "label": "Collective swarm",
        "source": REPO_ROOT / "configs" / "systematic" / "DO_CS01_swarm_C01_l05.yaml",
    },
    {
        "key": "DR01",
        "label": "Double ring",
        "source": REPO_ROOT / "configs" / "systematic" / "DO_DR01_dring_C01_l01.yaml",
    },
    {
        "key": "SM01",
        "label": "Single mill",
        "source": REPO_ROOT / "configs" / "systematic" / "DO_SM01_mill_C05_l01.yaml",
    },
    {
        "key": "DM01",
        "label": "Double mill",
        "source": REPO_ROOT / "configs" / "systematic" / "DO_DM01_dmill_C09_l05.yaml",
    },
    {
        "key": "EC02",
        "label": "Escape collapse",
        "source": REPO_ROOT / "configs" / "systematic" / "DO_EC02_esccol_C3_l05.yaml",
    },
    {
        "key": "ES01",
        "label": "Escape symmetric",
        "source": REPO_ROOT / "configs" / "systematic" / "DO_ES01_escsym_C3_l09.yaml",
    },
]

# The sweep intentionally excludes redundant "simplex + C2", because the
# evaluator already downgrades that pair to C0 before projection.
COMBOS = [
    ("raw", "C0", "none"),
    ("raw", "C1", "none"),
    ("raw", "C2", "none"),
    ("raw", "C0", "simplex"),
    ("raw", "C1", "simplex"),
    ("raw", "C0", "scale"),
    ("raw", "C1", "scale"),
    ("raw", "C2", "scale"),
    ("sqrt", "C0", "none"),
    ("sqrt", "C1", "none"),
    ("sqrt", "C2", "none"),
    ("sqrt", "C0", "simplex"),
    ("sqrt", "C1", "simplex"),
    ("sqrt", "C0", "scale"),
    ("sqrt", "C1", "scale"),
    ("sqrt", "C2", "scale"),
    ("log", "C0", "none"),
    ("log", "C0", "simplex"),
    ("log", "C0", "scale"),
    ("meansub", "C0", "none"),
]


def load_yaml(path: Path) -> dict:
    with open(path, encoding="utf-8") as handle:
        return yaml.safe_load(handle) or {}


def write_yaml(path: Path, comment_lines: list[str], data: dict) -> None:
    with open(path, "w", encoding="utf-8") as handle:
        handle.write("---\n")
        for line in comment_lines:
            handle.write(f"# {line}\n")
        handle.write("\n")
        yaml.dump(data, handle, default_flow_style=False, sort_keys=False)


def main() -> None:
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    manifest_entries: list[str] = []

    for regime in REGIMES:
        for transform, clamp_mode, mass_postprocess in COMBOS:
            cfg = load_yaml(regime["source"])

            cfg["sim"]["N"] = PARTICLE_COUNT

            rom_cfg = cfg["rom"]
            rom_cfg["density_transform"] = transform
            rom_cfg["density_transform_eps"] = 1e-10
            rom_cfg["mass_postprocess"] = mass_postprocess
            rom_cfg["save_unaligned_pod"] = False

            model_cfg = rom_cfg["models"]
            model_cfg["mvar"]["enabled"] = False

            lstm_cfg = model_cfg["lstm"]
            lstm_cfg["enabled"] = True
            lstm_cfg["lag"] = 5
            lstm_cfg["hidden_units"] = 64
            lstm_cfg["num_layers"] = 2

            if "wsindy" in cfg:
                cfg["wsindy"]["enabled"] = False

            eval_cfg = cfg["eval"]
            eval_cfg["clamp_mode"] = clamp_mode
            eval_cfg["save_forecasts"] = False
            eval_cfg["save_time_resolved"] = False

            exp_name = f"LPREP_{regime['key']}_{transform}_{clamp_mode}_{mass_postprocess}"
            cfg["experiment_name"] = exp_name

            comment_lines = [
                "LSTM preprocessing ablation derived from current systematic config",
                f"Base config: {regime['source'].relative_to(REPO_ROOT).as_posix()}",
                f"Regime: {regime['label']} ({regime['key']})",
                "Fixed architecture: h64_L2, lag=5, normalize_input=true",
                f"Sweep point: transform={transform}, clamp_mode={clamp_mode}, mass_postprocess={mass_postprocess}",
                f"Proxy particle count: sim.N={PARTICLE_COUNT}",
                "MVAR and WSINDy disabled; all other ROM/LSTM training settings inherit from the current systematic defaults.",
                "Auto-generated by scripts/create_lstm_preprocess_ablation_configs.py",
            ]

            out_path = OUTPUT_DIR / f"{exp_name}.yaml"
            write_yaml(out_path, comment_lines, cfg)
            manifest_entries.append(out_path.name)
            print(f"  Created: {out_path.name}")

    manifest_path = OUTPUT_DIR / "manifest.txt"
    with open(manifest_path, "w", encoding="utf-8") as handle:
        for entry in manifest_entries:
            handle.write(f"{entry}\n")

    print(f"\nGenerated {len(manifest_entries)} configs in {OUTPUT_DIR}")
    print(f"Manifest: {manifest_path}")


if __name__ == "__main__":
    main()
