#!/usr/bin/env python3
"""Generate LSTM size-ablation configs from the current systematic bases.

This suite keeps the current production preprocessing and training defaults
fixed, and only varies LSTM width/depth. The goal is to test whether lighter
models can match the current `64 x 2` reference before rerunning all
systematic Oscar experiments.
"""

from __future__ import annotations

from pathlib import Path

import yaml


REPO_ROOT = Path(__file__).resolve().parent.parent
OUTPUT_DIR = REPO_ROOT / "configs" / "LSTM_size_ablation"
PARTICLE_COUNT = 200

# Use the hardest d'Orsogna regimes already emphasized by the active sweeps.
REGIMES = [
    {
        "key": "CS01",
        "label": "Collective swarm",
        "source": REPO_ROOT / "configs" / "systematic" / "DO_CS01_swarm_C01_l05.yaml",
    },
    {
        "key": "DR01",
        "label": "Double ring",
        "source": REPO_ROOT / "configs" / "systematic" / "DO_DR01_dring_C01_l01.yaml",
    },
    {
        "key": "SM01",
        "label": "Single mill",
        "source": REPO_ROOT / "configs" / "systematic" / "DO_SM01_mill_C05_l01.yaml",
    },
    {
        "key": "DM01",
        "label": "Double mill",
        "source": REPO_ROOT / "configs" / "systematic" / "DO_DM01_dmill_C09_l05.yaml",
    },
    {
        "key": "EC02",
        "label": "Escape collapse",
        "source": REPO_ROOT / "configs" / "systematic" / "DO_EC02_esccol_C3_l05.yaml",
    },
    {
        "key": "ES01",
        "label": "Escape symmetric",
        "source": REPO_ROOT / "configs" / "systematic" / "DO_ES01_escsym_C3_l09.yaml",
    },
]

VARIANTS = [
    {
        "suffix": "h16_L1",
        "label": "Tiny width",
        "hidden_units": 16,
        "num_layers": 1,
    },
    {
        "suffix": "h32_L1",
        "label": "Small width",
        "hidden_units": 32,
        "num_layers": 1,
    },
    {
        "suffix": "h32_L2",
        "label": "Small + deep",
        "hidden_units": 32,
        "num_layers": 2,
    },
    {
        "suffix": "h64_L1",
        "label": "Wide shallow",
        "hidden_units": 64,
        "num_layers": 1,
    },
    {
        "suffix": "h64_L2",
        "label": "Current reference",
        "hidden_units": 64,
        "num_layers": 2,
    },
]


def load_yaml(path: Path) -> dict:
    with open(path) as handle:
        return yaml.safe_load(handle) or {}


def write_yaml(path: Path, comment_lines: list[str], data: dict) -> None:
    with open(path, "w") as handle:
        handle.write("---\n")
        for line in comment_lines:
            handle.write(f"# {line}\n")
        handle.write("\n")
        yaml.dump(data, handle, default_flow_style=False, sort_keys=False)


def main() -> None:
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    manifest_entries: list[str] = []

    for regime in REGIMES:
        base_cfg = load_yaml(regime["source"])
        lstm_cfg = base_cfg["rom"]["models"]["lstm"]

        for variant in VARIANTS:
            cfg = load_yaml(regime["source"])
            cfg["sim"]["N"] = PARTICLE_COUNT
            cfg["rom"]["models"]["mvar"]["enabled"] = False
            lstm_cfg = cfg["rom"]["models"]["lstm"]
            lstm_cfg["enabled"] = True
            lstm_cfg["hidden_units"] = variant["hidden_units"]
            lstm_cfg["num_layers"] = variant["num_layers"]
            if "wsindy" in cfg:
                cfg["wsindy"]["enabled"] = False

            exp_name = f"LSIZE_{regime['key']}_{variant['suffix']}"
            cfg["experiment_name"] = exp_name

            comment_lines = [
                "LSTM-only size ablation derived from current systematic config",
                f"Base config: {regime['source'].relative_to(REPO_ROOT).as_posix()}",
                f"Regime: {regime['label']} ({regime['key']})",
                f"Variant: {variant['label']} | hidden_units={variant['hidden_units']}, num_layers={variant['num_layers']}",
                f"Lighter proxy sweep: sim.N={PARTICLE_COUNT}",
                "MVAR disabled; all other preprocessing/training settings inherit from the current systematic defaults.",
                "Auto-generated by scripts/create_lstm_size_ablation_configs.py",
            ]

            out_path = OUTPUT_DIR / f"{exp_name}.yaml"
            write_yaml(out_path, comment_lines, cfg)
            manifest_entries.append(out_path.name)
            print(f"  Created: {out_path.name}")

    manifest_path = OUTPUT_DIR / "manifest.txt"
    with open(manifest_path, "w") as handle:
        for entry in manifest_entries:
            handle.write(f"{entry}\n")

    print(f"\nGenerated {len(manifest_entries)} configs in {OUTPUT_DIR}")
    print(f"Manifest: {manifest_path}")


if __name__ == "__main__":
    main()
