seed: 42
out_dir: outputs/grid
sim:
  N: 200
  Lx: 20.0
  Ly: 20.0
  bc: periodic
  T: 20.0
  dt: 0.01
  save_every: 20
  integrator: rk4
  neighbor_rebuild: 10
params:
  alpha: 1.5
  beta: 0.5
  Cr: 1.0
  Ca: 1.0
  lr: 1.0
  la: 1.0
  rcut_factor: 3.0
outputs:
  save_npz: true
  save_csv: true
  plots: false
  animate: false
  grid_density:
    enabled: false
grid:
  Cr: [0.1, 0.5, 0.9, 2.0, 3.0]
  lr: [0.1, 0.5, 0.9, 2.0, 3.0]
  Ca: [1.0]
  la: [1.0]
  reps: 1
