name: Render README Math

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  render:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install renderer dependencies
        run: |
          cd scripts
          npm init -y
          npm install mathjax-node@2.0.1

      - name: Run README renderer
        run: |
          cd scripts
          node render_readme_math.js

      - name: Commit rendered README and assets
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add README.rendered.md assets/readme || true
          git commit -m "chore: render README math (GitHub Action)" || true
          git push origin HEAD:main || true
